version: 2.1
orbs:
  ruby: circleci/ruby@2.0.0
  heroku: circleci/heroku@1.2.6
jobs:
  test:
    docker:
      - image: cimg/ruby:2.7.6
      - image: cimg/postgres:14.7
        environment:
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: lrus_test
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run:
          name: rake test
          command: |
            bundle exec rake dbcreate test
          environment:
            DATABASE_URL: postgresql://postgres@127.0.0.1:5432/lrus_test
workflows:
  version: 2
  default:
    jobs:
      - test
      - heroku/deploy-via-git:
          requires:
            - test
          filters:
            branches:
              only: master
